CREATE TABLE IF NOT EXISTS `newzdash_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `newzdash_tmuxlog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `PANE_NAME` varchar(255) NOT NULL,
  `PANE_STATE` tinyint(4) NOT NULL,
  `TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `newzdash_version` (
  `SCHEMA_VERSION` varchar(10) NOT NULL,
  PRIMARY KEY (`SCHEMA_VERSION`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;